### ISSUE TITLE
base64 line wrap defaults to 76 chars

### ISSUE THREAD

**Issue by tripatjain** [TIBCOSoftware/bpme-samples#16]
Ben Dorman ran into this issue while using the samples (submitting on his behalf) - 

Issue - LDAP DN can be > 76 characters

In the script bpm_start.sh invoked from the bpme-bpme.template CF template we've got this:
export BPM_DB_USERNAME_SECRET=`echo -n $BPM_DB_USERNAME | base64`
export BPM_DB_PASSWORD_SECRET=`echo -n $BPM_DB_PASSWORD | base64`
export LDAP_DN_SECRET=`echo -n $LDAP_DN | base64`
export LDAP_CLOUD_ADMIN_PASSWORD_SECRET=`echo -n $LDAP_CLOUD_ADMIN_PASSWORD | base64`

Cause - 
See man base64 or https://www.unix.com/man-page/linux/1/base64/

Solution - Use w0 flag in base64 command - 

echo -n '<string>' | base64 -w0

**Comment by mmyburgh** [comment]
I added this to the doc for others to see.
